parameters:
  aw.task_scheduler.background_job_repository: ~
  aw.task_scheduler.admin_name: 'Фоновые задачи'
  aw.task_scheduler.admin_group: settings
  aw.task_scheduler.uid: 'background-job'
  php_executable: /usr/bin/php

services:
  aw.task_scheduler.php_command_line:
    class: Accurateweb\TaskSchedulerBundle\Service\Command\PhpCommandLineResolver
    arguments: ['%kernel.root_dir%', '%php_executable%']

  aw.task_scheduler.daemon_pid_storage:
    class: Accurateweb\TaskSchedulerBundle\Service\DaemonPidStorage
    arguments: ['%kernel.root_dir%/../var/logs']

  aw.task_scheduler.launcher.factory:
    class: Accurateweb\TaskSchedulerBundle\Service\Command\CommandLineLauncherFactory
    arguments: ['@aw.task_scheduler.php_command_line', '@aw.task_scheduler.logger.factory', '%kernel.environment%']

  aw.task_scheduler.background_job_log_file_resolver:
    class: Accurateweb\TaskSchedulerBundle\Service\Logger\BackgroundJobLogFileResolver
    arguments: ['%kernel.root_dir%/../var/logs']

  aw.task_scheduler.logger.factory:
    class: Accurateweb\TaskSchedulerBundle\Service\Logger\BackgroundJobLoggerFactory
    arguments: ['@aw.task_scheduler.background_job_log_file_resolver']

  aw.task_scheduler.background_job_pool:
    class: Accurateweb\TaskSchedulerBundle\Service\BackgroundJob\BackgroundJobPool

  aw.task_scheduler.background_job_manager:
    class: Accurateweb\TaskSchedulerBundle\Service\BackgroundJob\BackgroundJobManager
    arguments: [~, '@aw.task_scheduler.background_job_pool', '@event_dispatcher', '@doctrine.orm.entity_manager']

  aw.task_scheduler.background_job_dispatcher:
    class: Accurateweb\TaskSchedulerBundle\Service\BackgroundJobDispatcher\BackgroundJobDispatcher
    arguments:
     - '@aw.task_scheduler.background_job_manager'
     - '@event_dispatcher'
     - '@doctrine.orm.entity_manager'
     - '@aw.task_scheduler.background_job_pool'
     - '@aw.task_scheduler.launcher.factory'
     - '%aw.task_scheduler.uid%'
     - '@aw.task_scheduler.dispatcher_logger'

  accurateweb_background_job.service_logger.background_job_dispatcher_logger_factory:
    class: Accurateweb\TaskSchedulerBundle\Service\Logger\BackgroundJobDispatcherLoggerFactory

  aw.task_scheduler.dispatcher_logger:
    class: Psr\Log\LoggerInterface
    factory: ['@accurateweb_background_job.service_logger.background_job_dispatcher_logger_factory', 'createLogger']
    arguments: ['%kernel.logs_dir%/background_job/daemon.log']

  aw.task_scheduler.interupt:
    class: Accurateweb\TaskSchedulerBundle\EventListener\InterruptJobs
    arguments: ['@doctrine.orm.entity_manager', '@aw.task_scheduler.background_job_manager']
    tags:
      - { name: kernel.event_listener, event: background_job.dispatch.start, method: onStart }

  aw.task_scheduler.admin:
    class: Accurateweb\TaskSchedulerBundle\Admin\BackgroundJobAdmin
    arguments: [~, ~, 'AccuratewebTaskSchedulerBundle:BackgroundJobCRUD', '@aw.task_scheduler.background_job_log_file_resolver']
    tags:
      - { name: sonata.admin, manager_type: orm, group: '%aw.task_scheduler.admin_group%', label: '%aw.task_scheduler.admin_name%' }

  aw.task_scheduler.repeat_listener:
    class: Accurateweb\TaskSchedulerBundle\EventListener\RepeatJobListener
    arguments: ['@aw.task_scheduler.background_job_manager']
    tags:
      - { name: kernel.event_listener, event: job.end, method: onJobEnd }